name:                treecheck
version:             0.0.1.0
github:              "gillchristian/treecheck"
license:             MIT
author:              "Christian Gill"
maintainer:          "gillchristiang@gmail.com"
copyright:           "2022 Christian Gill"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/gillchristian/treecheck#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- casing
- bytestring
- containers
- directory
- filepath
- nonempty-containers
- optparse-applicative
- process
- text
- yaml

library:
  source-dirs: src

executables:
  treecheck:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - treecheck

tests:
  treecheck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - treecheck
